### ISSUE TITLE
Where can I use your best practices?

### ISSUE THREAD

**Issue by varkrift** [egnaf/data-structures#8]
Hi, @egnaf !
Where can I use your best practices?

**Comment by egnaf** [comment]
Hi, @varkrift! Thanks for you question.

Data structures are needed in any programming language, not just Java. But, I will post examples of work in the Java language. Therefore, you can only use the Java language. But, I plan to lay out examples in other languages, such as C++, Kotlin, Scala, Go and etc.


> Hi, @egnaf !
> Where can I use your best practices?
